INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'T-Rex', 'Papo_T-Rex.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Chariot', 'Papo_Chariot.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dragon', 'Papo_Dragon.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Mammoth', 'Papo_Mammoth.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Mammoth', 'Papo_Mammoth2.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses1.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses2.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses3.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses4.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses5.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses6.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox1.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox2.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox3.jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (7).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (8).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (7).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (8).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (9).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (7).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (8).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (9).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Rock Polisher', 'rock_polisher (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Rock Polisher', 'rock_polisher (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (5).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (6).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (7).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (8).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (9).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (1).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (2).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (3).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (4).jpg'
INSERT INTO tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Mat', 'cowboys mat.jpg'
