INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'T-Rex', 'DESCRIPTION PENDING', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Chariot', 'DESCRIPTION PENDING', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Dragon', 'DESCRIPTION PENDING', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Mammoth', 'DESCRIPTION PENDING', 7, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'WoodenToys', 'Small Box with Horses', 'Small box with horse motif on top and sides.  Perfect for the tooth fairy or to keep or give tiny treasures.  Mirror on inside of cover, and jewelry pillow.  2.25 inches square.', 5, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'WoodenToys', 'Small Fish Treasure Box', 'Small box with carved fish and tight fitting lid that slides on and off.  Highly polished wood with rounded edges.  Small heart on the reverse.  Perfect for the tooth fairy or to keep or give tiny treasures.  About 2 inches by 1.5 inches.', 8, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Apollo 11 Rocket', 'Apollo 11 recreation including a realistic Saturn V rocket, Eagle Landing Module and Columbia Command/Service Module, launch pad and lunar surface.', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Football', 'Dallas Cowboys Locker', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Musical', 'Conga Drums', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Football', 'Dallas Cowboys Mat', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Musical', 'Yamaha Electronic Drum Set', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Elastic Power Construction Set', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Football', 'Football Helmet', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Light Saber', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Musical', 'Folding Music Stand', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Compact Security Safe', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Rock Polisher', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Football', 'Shoulder Pads', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Unicycle', 'DESCRIPTION PENDING', 0, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Puppets', 'Chicks in Nest Finger Puppet', 'Three finger puppet bluebird chicks in a nest, by Folkmanis. Like new, tag on.  Retails for $14.50.', 5, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Puppets', 'Dinosaur Hand Puppets', 'Large, plush tyrannosaurus and pterodactyl hand puppets by Folkmanis.  Retails for $60, $40 on Amazon.', 30, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo1', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo2', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo3', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo4', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo5', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo6', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo7', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo8', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo9', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo10', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo11', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo12', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo13', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo14', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo15', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo16', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo17', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo18', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Figurines', 'Papo19', 'Assorted figurines from the French Papo and German Schleich toymakers, mostly in virtually new condition.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'WoodenToys', 'Small Wooden Toys', 'Three wooden toys include a slide whistle, a rubber band gun and rubber band trebuchet.', 5, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'WoodenToys', 'Magnetic Calendar', 'Magnetic calendar with magnets for days of the month, month, season, holidays, special events, appointments, lessons, etc.  Does not have current and future year magnets but we think they are available from the manufacturer.', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Musical Snow Globe', 'Beautiful musical snow globe.  Inside globe is angel playing a flute with fawn and hare.  Like new (has antique finish).  5.5” tall. ', 12, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Other', 'Alamo Set', 'Plastic recreation of the Alamo, complete with two armies, camp supplies, cannons, etc..', 10, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Lego', 'Harry Potter - The Burrow (#4840)', 'Retails for $250, available used on BrickLink.com for $120.', 60, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Lego', 'Harry Potter - Hogwarts Express (#4841)', 'Retails for $150, available used on Bricklink.com for $118.', 60, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Lego', 'Harry Potter - Hogwarts Castle (#4842)', 'Retired, available used on BrickLink.com for $212-$500+.', 150, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Lego', 'Star Wars - Millenium Falcon (#7965)', 'Retails for $150, available used on BrickLink.com for $120-$150.', 80, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Lego', 'Dwarve''s Mine Castle (#7036)', 'Retails for $135, available used on BrickLink for $60-$160.', 45, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Barbarian', '1 barbarian, horse and accessories. Kit #4436, Retail $9.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Cannon Guard', '1 knight, cannon and cannon balls.  Kit #?  Retail about $7.', 3, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Captive Prince (#3328)', 'Knight, prince, camp accessories, missing keys.  Kit #3328, Retail $18.', 9, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Dragon Attack Cannon (#3320)', '2 nights, cannon and accessories. 2 available.  Kit #3320.  Retail $12.', 6, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Knight Carrying Case', '1 knight, 1 horse and many accessories, but not sure all accessories are accounted for.  Kit #?. Retail $32', 15, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Knights', '2 knights and accessories.  Kit #?. Retail about $10', 5, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Knight''s battle chest (#5784)', 'Similar to the one shown, but Knight, not Viking, themed.  Kit #5784.  Retail $27.', 13, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Knight''s Dungeon (#5794, similar to this one)', 'Similar to one shown, with dungeon, battering ram, breakaway wall and cannon.  Kit #5794. Retail $100.', 50, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Prince', '1 prince and accessories.  Kit #?.  Retail about $5.', 2, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Roman Gladiators (#5824)', '2 gladiators and accessories.  Kit #5824.  Retail $15.', 7, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Silver Knight (#4434?)', 'Similar to kit shown.  Kit #4434?.  Retail $9.', 4, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Knights - Treasure Transport', 'Wagon, 2 horses, 3 knights, chsest and coins.  Kit #3314.  Retail $25.', 12, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Modern - Airboat', 'Airboat/swamp boat with 2 pilots and toolbox.  Kit #?.  Retail about $25.', 12, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Modern - Grocery Delivery Van (#3204)', 'Delivery van with driver, dolly, crates of food and drinks. Missing antenna and plastic piece in middle of roof.  Kit #3204. Retail $84', 40, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Modern - Soccer shootout case', '2 specialized figures with kicking action, goal, barriers, balls and carrying case.  Kit #4701. Retail $12.', 6, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Pirates - Pirates', '2 pirates and accessories.  Kit #.  Retail about $10.', 5, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Pirates - Treasure Island (#5728)', 'Island, 2 pirates, skeleton, treasure and accessories. Missing treasure chest.  Kit #5728.  Retail $25.', 12, 1
INSERT INTO tc.tblItems(TypeName, ItemName, ItemDescription, ItemPrice, IsAvailable) SELECT 'Playmobile', 'Viking - Green Knight and Viking (#5828)', '2 nights and accessories, viking has been substituted for knight.  Kit# 5828. Retail $11.', 5, 1
