INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'T-Rex', 'Papo_T-Rex.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Chariot', 'Papo_Chariot.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dragon', 'Papo_Dragon.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Mammoth', 'Papo_Mammoth.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Mammoth', 'Papo_Mammoth2.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses1.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses2.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses3.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses4.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses5.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Box with Horses', 'SmallBoxHorses6.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox1.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox2.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Fish Treasure Box', 'SmallFishBox3.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (7).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Apollo 11 Rocket', 'Apollo11 (8).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Conga Drums', 'Congas (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (7).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (8).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Locker', 'Cowboys locker (9).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Yamaha Electronic Drum Set', 'Drums (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Elastic Power Construction Set', 'elastic_power (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Football Helmet', 'helmet (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Light Saber', 'light_saber (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Folding Music Stand', 'music stand (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (7).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (8).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Compact Security Safe', 'security_safe (9).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Rock Polisher', 'rock_polisher (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Rock Polisher', 'rock_polisher (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (5).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (6).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (7).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (8).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Shoulder Pads', 'shoulder_pads (9).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (1).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (2).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (3).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Unicycle', 'unicycle (4).jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dallas Cowboys Mat', 'cowboys mat.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Chicks in Nest Finger Puppet', 'DSC_0921.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dinosaur Hand Puppets', 'DSC_0926.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dinosaur Hand Puppets', 'DSC_0929.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dinosaur Hand Puppets', 'DSC_0930.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dinosaur Hand Puppets', 'DSC_0931.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dinosaur Hand Puppets', 'DSC_0934.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo1', 'DSC_0053.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo2', 'DSC_0054.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo3', 'DSC_0055.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo4', 'DSC_0056.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo5', 'DSC_0057.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo6', 'DSC_0058.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo7', 'DSC_0059.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo8', 'DSC_0060.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo9', 'DSC_0061.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo10', 'DSC_0062.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo11', 'DSC_0063.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo12', 'DSC_0064.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo13', 'DSC_0065.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo14', 'DSC_0066.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo15', 'DSC_0067.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo16', 'DSC_0068.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo17', 'DSC_0069.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo18', 'DSC_0189.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Papo19', 'DSC_0190.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Wooden Toys', 'DSC_0736.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Wooden Toys', 'DSC_0738.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Small Wooden Toys', 'DSC_0740.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0182.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0183.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0184.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0185.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0186.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0187.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0188.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0188b.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Magnetic Calendar', 'DSC_0188c.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1183.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1184.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1185.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1186.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1187.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Musical Snow Globe', 'DSC_1188.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0070.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0071.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0072.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0073.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0074.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0075.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0076.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Alamo Set', 'DSC_0077.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Harry Potter - The Burrow (#4840)', '4840.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Harry Potter - Hogwarts Express (#4841)', '4841.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Harry Potter - Hogwarts Castle (#4842)', '4842.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Star Wars - Millenium Falcon (#7965)', '7965.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Dwarve''s Mine Castle (#7036)', '7036.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Barbarian', '4436.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Cannon Guard', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Captive Prince (#3328)', '3328.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Dragon Attack Cannon (#3320)', '3320.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Knight Carrying Case', 'knight_carrying_case.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Knights', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Knight''s battle chest (#5784)', 'for_5784.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Knight''s Dungeon (#5794, similar to this one)', 'for_5794.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Prince', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Roman Gladiators (#5824)', '5824.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Silver Knight (#4434?)', '4436.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Knights - Treasure Transport', '3314.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Modern - Airboat', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Modern - Grocery Delivery Van (#3204)', '3204.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Modern - Soccer shootout case', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Pirates - Pirates', 'playmobil-logo.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Pirates - Treasure Island (#5728)', '5728.jpg'
INSERT INTO tc.tblImages(ItemName, ImageFileName) SELECT 'Viking - Green Knight and Viking (#5828)', '5828.jpg'
