INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'PuppetsAndFigurines', 'Puppets and Figurines'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'WoodenToys', 'Wooden Toys'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'Other', 'Various Other Toys'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'Playmobile', 'Playmobile Kits'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'Lego', 'Lego Kits'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'Football', 'Football Toys'
INSERT INTO tblTypes(TypeName, TypeDescription) SELECT 'Musical', 'Musical Items'
